#ifndef REDSTRAIN_MOD_ALGORITHM_MODINFO_HPP
#define REDSTRAIN_MOD_ALGORITHM_MODINFO_HPP

#include <redstrain/redmond/LibraryDependency.hpp>

#include "api.hpp"

#define REDSTRAIN_MOD_ALGORITHM_STATIC_VERSION_MAJOR 0u
#define REDSTRAIN_MOD_ALGORITHM_STATIC_VERSION_MINOR 1u

namespace redengine {
namespace algorithm {

	REDSTRAIN_DECLARE_MODULE_VERSION(REDSTRAIN_ALGORITHM_API)

}}

#endif /* REDSTRAIN_MOD_ALGORITHM_MODINFO_HPP */
