#ifndef REDSTRAIN_MOD_REDMOND_MACROS_HPP
#define REDSTRAIN_MOD_REDMOND_MACROS_HPP

#if XAKE_COMPILER == XAKE_COMPILER_MSVC
#define REDSTRAIN_NEEDS_DLLEXPORT
#endif /* !MSVC */

#endif /* REDSTRAIN_MOD_REDMOND_MACROS_HPP */
