#ifndef REDSTRAIN_MOD_REDMOND_MACROS_HPP
#define REDSTRAIN_MOD_REDMOND_MACROS_HPP

#include "environment.hpp"

#ifdef REDSTRAIN_ENV_COMPILER_MSVC
#define REDSTRAIN_NEEDS_DLLEXPORT
#endif /* !MSVC */

#endif /* REDSTRAIN_MOD_REDMOND_MACROS_HPP */
