#ifndef REDSTRAIN_MOD_REDMOND_MODINFO_HPP
#define REDSTRAIN_MOD_REDMOND_MODINFO_HPP

#include "LibraryDependency.hpp"

#define REDSTRAIN_MOD_REDMOND_STATIC_VERSION_MAJOR 0u
#define REDSTRAIN_MOD_REDMOND_STATIC_VERSION_MINOR 1u

namespace redengine {
namespace redmond {

	REDSTRAIN_DECLARE_MODULE_VERSION(REDSTRAIN_REDMOND_API)

}}

#endif /* REDSTRAIN_MOD_REDMOND_MODINFO_HPP */
