#ifndef REDSTRAIN_MOD_ERROR_TWEAKS_HPP
#define REDSTRAIN_MOD_ERROR_TWEAKS_HPP

#define REDSTRAIN_ERROR_PRINT_STACK_TRACES_ENVVAR "REDSTRAIN_PRINT_STACK_TRACES"

#endif /* REDSTRAIN_MOD_ERROR_TWEAKS_HPP */
