#ifndef REDSTRAIN_MOD_REDMOND_UNMANGLE_SPECIALSYMBOLMANGLESTYLE_HPP
#define REDSTRAIN_MOD_REDMOND_UNMANGLE_SPECIALSYMBOLMANGLESTYLE_HPP

namespace redengine {
namespace redmond {
namespace unmangle {

	enum SpecialSymbolMangleStyle {
		SSMS_REDSTRAIN,
		SSMS_GCC3
	};

}}}

#endif /* REDSTRAIN_MOD_REDMOND_UNMANGLE_SPECIALSYMBOLMANGLESTYLE_HPP */
