#ifndef REDSTRAIN_TOOLS_UNMANGLE_BLOBDEPEND_HPP
#define REDSTRAIN_TOOLS_UNMANGLE_BLOBDEPEND_HPP

#if defined(REDSTRAIN_BLOBFUL_BUILD) && defined(HAVE_REDSTRAIN_PLATFORM_L10N_DEPENDENCY) && defined(HAVE_REDSTRAIN_CHARSETS_DEPENDENCY) && defined(HAVE_REDSTRAIN_IO_L10N_DEPENDENCY) && defined(HAVE_REDSTRAIN_ERROR_L10N_DEPENDENCY) && defined(HAVE_REDSTRAIN_STACKTRACE_L10N_DEPENDENCY)
#define HAVE_ALL_BLOB_DEPENDENCIES
#endif

bool areAllBlobDependenciesPresent();

#endif /* REDSTRAIN_TOOLS_UNMANGLE_BLOBDEPEND_HPP */
