#ifndef REDSTRAIN_MOD_DAMNATION_BOXSYMBOL_HPP
#define REDSTRAIN_MOD_DAMNATION_BOXSYMBOL_HPP

#include <redstrain/text/types.hpp>

#include "api.hpp"

namespace redengine {
namespace damnation {

	enum REDSTRAIN_DAMNATION_API BoxSymbol {
		BS_BLANK,
		BS_HORIZONTAL_BAR,
		BS_VERTICAL_BAR,
		BS_LEFT_UPPER_CORNER,
		BS_RIGHT_UPPER_CORNER,
		BS_LEFT_LOWER_CORNER,
		BS_RIGHT_LOWER_CORNER,
		BS_LEFT_T,
		BS_RIGHT_T,
		BS_UPPER_T,
		BS_LOWER_T,
		BS_CROSS,
		BS_DOUBLE_HORIZONTAL_BAR,
		BS_DOUBLE_VERTICAL_BAR,
		BS_DOUBLE_LEFT_UPPER_CORNER,
		BS_DOUBLE_RIGHT_UPPER_CORNER,
		BS_DOUBLE_LEFT_LOWER_CORNER,
		BS_DOUBLE_RIGHT_LOWER_CORNER,
		BS_DOUBLE_LEFT_T,
		BS_DOUBLE_RIGHT_T,
		BS_DOUBLE_UPPER_T,
		BS_DOUBLE_LOWER_T,
		BS_DOUBLE_CROSS,
		BS_LEFT_UPPER_CORNER_DOUBLE_TOP,
		BS_LEFT_UPPER_CORNER_DOUBLE_LEFT,
		BS_RIGHT_UPPER_CORNER_DOUBLE_TOP,
		BS_RIGHT_UPPER_CORNER_DOUBLE_RIGHT,
		BS_LEFT_LOWER_CORNER_DOUBLE_BOTTOM,
		BS_LEFT_LOWER_CORNER_DOUBLE_LEFT,
		BS_RIGHT_LOWER_CORNER_DOUBLE_BOTTOM,
		BS_RIGHT_LOWER_CORNER_DOUBLE_RIGHT,
		BS_LEFT_T_DOUBLE_RIGHT,
		BS_LEFT_T_DOUBLE_LEFT,
		BS_RIGHT_T_DOUBLE_LEFT,
		BS_RIGHT_T_DOUBLE_RIGHT,
		BS_UPPER_T_DOUBLE_BOTTOM,
		BS_UPPER_T_DOUBLE_TOP,
		BS_LOWER_T_DOUBLE_TOP,
		BS_LOWER_T_DOUBLE_BOTTOM,
		BS_CROSS_DOUBLE_HORIZONTAL,
		BS_CROSS_DOUBLE_VERTICAL,
		BS_CHECKBOX_EMPTY,
		BS_CHECKBOX_HALF,
		BS_CHECKBOX_FULL,
		BS_TRIANGLE_UP,
		BS_TRIANGLE_DOWN,
		BS_TRIANGLE_LEFT,
		BS_TRIANGLE_RIGHT,
		BS_BIG_CHECKBOX_EMPTY,
		BS_BIG_CHECKBOX_FULL,
		BS_DAGGER,
		BS_HOURGLASS,
		BS_INFINITY,
		BS_LEFT_ARROW,
		BS_RIGHT_ARROW,
		BS_UP_ARROW,
		BS_DOWN_ARROW,
		BS_HORIZONTAL_ARROW,
		BS_VERTICAL_ARROW,
		BS_TAB_ARROW,
		BS_RETURN_ARROW,
		BS_FULL_BLOCK,
		BS_LOWER_BLOCK_18,
		BS_LOWER_BLOCK_28,
		BS_LOWER_BLOCK_38,
		BS_LOWER_BLOCK_48,
		BS_LOWER_BLOCK_58,
		BS_LOWER_BLOCK_68,
		BS_LOWER_BLOCK_78,
		BS_LEFT_BLOCK_18,
		BS_LEFT_BLOCK_28,
		BS_LEFT_BLOCK_38,
		BS_LEFT_BLOCK_48,
		BS_LEFT_BLOCK_58,
		BS_LEFT_BLOCK_68,
		BS_LEFT_BLOCK_78
	};

	REDSTRAIN_DAMNATION_API char getBoxChar8(BoxSymbol);
	REDSTRAIN_DAMNATION_API text::Char16 getBoxChar16(BoxSymbol);

}}

#endif /* REDSTRAIN_MOD_DAMNATION_BOXSYMBOL_HPP */
