#ifndef REDSTRAIN_MOD_DAMNATION_MODINFO_HPP
#define REDSTRAIN_MOD_DAMNATION_MODINFO_HPP

#include <redstrain/redmond/LibraryDependency.hpp>

#include "api.hpp"

#define REDSTRAIN_MOD_DAMNATION_STATIC_VERSION_MAJOR 0u
#define REDSTRAIN_MOD_DAMNATION_STATIC_VERSION_MINOR 1u

namespace redengine {
namespace damnation {

	REDSTRAIN_DECLARE_MODULE_VERSION(REDSTRAIN_DAMNATION_API)

}}

#endif /* REDSTRAIN_MOD_DAMNATION_MODINFO_HPP */
