#ifndef REDSTRAIN_MOD_DAMNATION_TWEAKS_HPP
#define REDSTRAIN_MOD_DAMNATION_TWEAKS_HPP

#define REDSTRAIN_DAMNATION_UNIXTERMINALBINDING_BLOCK_SIZE 128u

#endif /* REDSTRAIN_MOD_DAMNATION_TWEAKS_HPP */
