#ifndef REDSTRAIN_MOD_CMDLINE_MODINFO_HPP
#define REDSTRAIN_MOD_CMDLINE_MODINFO_HPP

#include <redstrain/redmond/LibraryDependency.hpp>

#include "api.hpp"

#define REDSTRAIN_MOD_CMDLINE_STATIC_VERSION_MAJOR 0u
#define REDSTRAIN_MOD_CMDLINE_STATIC_VERSION_MINOR 1u

namespace redengine {
namespace cmdline {

	REDSTRAIN_DECLARE_MODULE_VERSION(REDSTRAIN_CMDLINE_API)

}}

#endif /* REDSTRAIN_MOD_CMDLINE_MODINFO_HPP */
