#ifndef REDSTRAIN_MOD_IO_TWEAKS_HPP
#define REDSTRAIN_MOD_IO_TWEAKS_HPP

#define REDSTRAIN_IO_DEFAULT_COPY_BUFFER_BYTES 512u
#define REDSTRAIN_IO_DEFAULT_LINE_BUFFER_RECORDS 512u

#endif /* REDSTRAIN_MOD_IO_TWEAKS_HPP */
