#ifndef REDSTRAIN_MOD_TEXT_FORMATTINGSTRINGOPTION_HPP
#define REDSTRAIN_MOD_TEXT_FORMATTINGSTRINGOPTION_HPP

#include "api.hpp"

namespace redengine {
namespace text {

	enum REDSTRAIN_TEXT_API FormattingStringOption {
		FSO_NAN,
		FSO_POSITIVE_INFINITY,
		FSO_NEGATIVE_INFINITY
	};

}}

#endif /* REDSTRAIN_MOD_TEXT_FORMATTINGSTRINGOPTION_HPP */
