#ifndef REDSTRAIN_MOD_TEXT_TWEAKS_HPP
#define REDSTRAIN_MOD_TEXT_TWEAKS_HPP

#define REDSTRAIN_TEXT_TRANSCODE_BUFFER_BYTES 256u
#define REDSTRAIN_TEXT_CODEC_STREAM_BUFFER_SIZE 128u

#endif /* REDSTRAIN_MOD_TEXT_TWEAKS_HPP */
