#ifndef REDSTRAIN_MOD_CALENDAR_CALENDARPRECISION_HPP
#define REDSTRAIN_MOD_CALENDAR_CALENDARPRECISION_HPP

namespace redengine {
namespace calendar {

	enum CalendarPrecision {
		PREC_DAY,
		PREC_MINUTE,
		PREC_SECOND,
		PREC_MILLISECOND,
		PREC_MICROSECOND
	};

}}

#endif /* REDSTRAIN_MOD_CALENDAR_CALENDARPRECISION_HPP */
