#ifndef REDSTRAIN_MOD_CALENDAR_FORMATMESSAGEKEY_HPP
#define REDSTRAIN_MOD_CALENDAR_FORMATMESSAGEKEY_HPP

namespace redengine {
namespace calendar {

	enum FormatMessageKey {
		FMK_TSO_MON,
		FMK_TSO_TUE,
		FMK_TSO_WED,
		FMK_TSO_THU,
		FMK_TSO_FRI,
		FMK_TSO_SAT,
		FMK_TSO_SUN,
		FMK_TSO_MONDAY,
		FMK_TSO_TUESDAY,
		FMK_TSO_WEDNESDAY,
		FMK_TSO_THURSDAY,
		FMK_TSO_FRIDAY,
		FMK_TSO_SATURDAY,
		FMK_TSO_SUNDAY,
		FMK_TSO_JAN,
		FMK_TSO_FEB,
		FMK_TSO_MAR,
		FMK_TSO_APR,
		FMK_TSO_MAY_S,
		FMK_TSO_JUN,
		FMK_TSO_JUL,
		FMK_TSO_AUG,
		FMK_TSO_SEP,
		FMK_TSO_OCT,
		FMK_TSO_NOV,
		FMK_TSO_DEC,
		FMK_TSO_JANUARY,
		FMK_TSO_FEBRUARY,
		FMK_TSO_MARCH,
		FMK_TSO_APRIL,
		FMK_TSO_MAY,
		FMK_TSO_JUNE,
		FMK_TSO_JULY,
		FMK_TSO_AUGUST,
		FMK_TSO_SEPTEMBER,
		FMK_TSO_OCTOBER,
		FMK_TSO_NOVEMBER,
		FMK_TSO_DECEMBER,
		FMK_TSO_AM,
		FMK_TSO_PM,
		FMK_FORMAT_SHORT_DATE,
		FMK_FORMAT_MEDIUM_DATE,
		FMK_FORMAT_LONG_DATE,
		FMK_FORMAT_FULL_DATE,
		FMK_FORMAT_SHORT_TIME,
		FMK_FORMAT_MEDIUM_TIME,
		FMK_FORMAT_LONG_TIME,
		FMK_FORMAT_FULL_TIME,
		FMK_FORMAT_SHORT_DATETIME,
		FMK_FORMAT_MEDIUM_DATETIME,
		FMK_FORMAT_LONG_DATETIME,
		FMK_FORMAT_FULL_DATETIME,
		FMK__LAST
	};

}}

#endif /* REDSTRAIN_MOD_CALENDAR_FORMATMESSAGEKEY_HPP */
