#ifndef REDSTRAIN_MOD_CALENDAR_LOCALIZEDTIMEFORMAT_HPP
#define REDSTRAIN_MOD_CALENDAR_LOCALIZEDTIMEFORMAT_HPP

namespace redengine {
namespace calendar {

	enum LocalizedTimeFormat {
		LTF_SHORT_DATE,
		LTF_MEDIUM_DATE,
		LTF_LONG_DATE,
		LTF_FULL_DATE,
		LTF_SHORT_TIME,
		LTF_MEDIUM_TIME,
		LTF_LONG_TIME,
		LTF_FULL_TIME,
		LTF_SHORT_DATETIME,
		LTF_MEDIUM_DATETIME,
		LTF_LONG_DATETIME,
		LTF_FULL_DATETIME
	};

}}

#endif /* REDSTRAIN_MOD_CALENDAR_LOCALIZEDTIMEFORMAT_HPP */
