#ifndef REDSTRAIN_MOD_CALENDAR_MODINFO_HPP
#define REDSTRAIN_MOD_CALENDAR_MODINFO_HPP

#include <redstrain/redmond/LibraryDependency.hpp>

#include "api.hpp"

#define REDSTRAIN_MOD_CALENDAR_STATIC_VERSION_MAJOR 0u
#define REDSTRAIN_MOD_CALENDAR_STATIC_VERSION_MINOR 1u

namespace redengine {
namespace calendar {

	REDSTRAIN_DECLARE_MODULE_VERSION(REDSTRAIN_CALENDAR_API)

}}

#endif /* REDSTRAIN_MOD_CALENDAR_MODINFO_HPP */
