#ifndef REDSTRAIN_MOD_CALENDAR_TIMESTRINGOPTION_HPP
#define REDSTRAIN_MOD_CALENDAR_TIMESTRINGOPTION_HPP

#include "api.hpp"

namespace redengine {
namespace calendar {

	enum REDSTRAIN_CALENDAR_API TimeStringOption {
		TSO_MON,
		TSO_TUE,
		TSO_WED,
		TSO_THU,
		TSO_FRI,
		TSO_SAT,
		TSO_SUN,
		TSO_MONDAY,
		TSO_TUESDAY,
		TSO_WEDNESDAY,
		TSO_THURSDAY,
		TSO_FRIDAY,
		TSO_SATURDAY,
		TSO_SUNDAY,
		TSO_JAN,
		TSO_FEB,
		TSO_MAR,
		TSO_APR,
		TSO_MAY_S,
		TSO_JUN,
		TSO_JUL,
		TSO_AUG,
		TSO_SEP,
		TSO_OCT,
		TSO_NOV,
		TSO_DEC,
		TSO_JANUARY,
		TSO_FEBRUARY,
		TSO_MARCH,
		TSO_APRIL,
		TSO_MAY,
		TSO_JUNE,
		TSO_JULY,
		TSO_AUGUST,
		TSO_SEPTEMBER,
		TSO_OCTOBER,
		TSO_NOVEMBER,
		TSO_DECEMBER,
		TSO_AM,
		TSO_PM
	};

}}

#endif /* REDSTRAIN_MOD_CALENDAR_TIMESTRINGOPTION_HPP */
